version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "9999:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: purmp

  redis:
    image: redis
    ports:
      - "9998:6379"